apoio/apoio/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from apoio import views


urlpatterns = [
    url(r'^coletores/', include('coletores.urls')),
    url(r'^faqs/', include('faqs.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^$', views.index, name='index'),
]

apoio/coletores/urls.py
from django.conf.urls import url
from . import views



urlpatterns = [
    url(r'^$', views.index, name='index'),
]

apoio/faqs/urls.py
from django.conf.urls import url
from . import views


app_name = 'faqs'
urlpatterns = [
        ## /faqs/ the timely ordered list of approved questions
        url(r'^$', views.index, name='index'),

        ## /faqs/$question_id/ the question id, visible if pending and not-answered
        url(r'^(?P<question_id>[0-9]+)/$', views.detail, name='detail'),

        ## /faqs/$question_id/results/ the question id, visible if aproved and answered
        url(r'^(?P<question_id>[0-9]+)/results/$', views.results, name='results'),

        ## /faqs/$question_id/ask/ the question id, form to ask a question
        url(r'^(?P<question_id>[0-9]+)/ask/$', views.ask, name='ask'),
]

apoio/coletores/models.py
from django.db import models



class Collector(models.Model):
    BOARD = 'BO'
    POINT = 'PO'

    COLLECTOR_TYPE = ( (BOARD, 'Comitê de Coleta'), (POINT, 'Ponto de Coleta'), )

    text_description = models.CharField(max_length=300)
    collector_type   = models.CharField(max_length=2, choices=COLLECTOR_TYPE, default=POINT)
    pub_date         = models.DateTimeField('date published')

    def is_upperclass(self):
        return self.collector_type in (self.BOARD, self.POINT)


class Detail(models.Model):
    collector       = models.ForeignKey(Collector, on_delete=models.CASCADE)
    chairman_name   = models.TextField()
    street_name     = models.TextField()
    street_cep      = models.PositiveIntegerField(default=0,)
    region_place    = models.CharField(max_length=300)
    city_name       = models.TextField() ## TODO: find a pre computed list
    estate_name     = models.TextField() ## TODO: find a pre computed list
    telefone_number = models.PositiveIntegerField(default=0,)
    website_address = models.CharField(max_length=300)
    email_address   = models.CharField(max_length=300)
    coordinates     = models.CharField(max_length=300)

apoio/faqs/models.py
from django.db import models
from django.core.validators import MaxValueValidator
from django.utils import timezone



class Question(models.Model):
    PENDING  = 'PE'
    APPROVED = 'AP'

    QUESTION_STATUS = ( (PENDING, 'Pending'), (APPROVED, 'Approved'), )

    question_text   = models.CharField(max_length=200)
    question_status = models.CharField(max_length=2, choices=QUESTION_STATUS, default=PENDING)
    pub_date        = models.DateTimeField('date published')

    def is_upperclass(self):
        return self.question_status in (self.PENDING, self.APPROVED)

    def was_published_recently(self):
        if self.question_status == self.APPROVED:
            return self.pub_date >= timezone.now() - datetime.timedelta(days=1)

    def __str__(self):
        return self.question_text


class Answer(models.Model):
    question     = models.ForeignKey(Question, on_delete=models.CASCADE)
    answer_text  = models.TextField()
    answer_vote  = models.PositiveIntegerField(default=0, validators=[MaxValueValidator(100),])
    pub_date     = models.DateTimeField('date published')

    def was_answered_recently(self):
        return self.pub_date >= timezone.now() - datetime.timedelta(days=1)

    def __str__(self):
        return self.answer_text

apoio/apoio/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.shortcuts import render


def index(request):
    return render(request, 'index.html', {'SIGLA': 'PIRATAS', 'NOME': 'Campanha de Coleta de Assinaturas'})

apoio/coletores/views.py
from django.shortcuts import render
from django.http import HttpResponse


def index(request):
    return HttpResponse("HALLO")

apoio/faqs/views.py
from django.template.loader import get_template
from django.shortcuts import render
from django.http import HttpResponse
from django.core.urlresolvers import reverse
from .models import Question, Answer


def index(request):
    latest_question_list = Question.objects.order_by('-pub_date')[:5]
    template = get_template('faqs/index.html')
    context = {
        'latest_question_list': latest_question_list,
    }
    return HttpResponse(template.render(context, request))


def detail(request, question_id):
    try:
        question = Question.objects.get(pk=question_id)
        answer   = Answer.objects.get(pk=question_id)
    except Question.DoesNotExist:
        raise Http404("Essa pergunta não foi feita ou ainda não foi respondida.")
    return render(request, 'faqs/detail.html', {'question': question, 'answer': answer})


def results(request, question_id):
    response = "Esse é o resultado da pergunta %s."
    return HttpResponse(response % question_id)


def ask(request, question_id):
    return HttpResponse("Vote na pergunta %s." % question_id)

apoio/apoio/templates/apoio/contatos.html
<section id="contatos" layout="center fix">
    <div layout="half left" ontablet="full-width" onmobile="full-width">
        <h1 layout="h-margin-15">
          <i class="material-icons" style="vertical-align: middle;">chat</i>
            Fale com os organizadores
        </h1>
        <p layout="h-margin-15">
            O Comitê Nacional da nossa campanha de coleta mantém um grupo <b>Telegram</b>,
            entre em contato conosco <a href='https://telegram.me/apoiopirata'>https://telegram.me/apoiopirata</a>
        </p>
        <ul>
            <li layout="v-margin-5">
                Entre também no site principal do partido, visite <a href='https://partidopirata.org/'>partidopirata.org</a>
            </li>
            <li layout="v-margin-5">
                Encontre-nos via <b>Twitter</b>, visite <a href="https://twitter.com/PartidoPirataBR">https://twitter.com/PartidoPirataBR</a>
            </li>
            <li layout="v-margin-5">
                Se você prefere <b>Facebook</b>, visite <a href='https://www.facebook.com/PartidoPirata.BR'>https://www.facebook.com/PartidoPirata.BR</a>
            </li>
        </ul>
    </div>

    <div layout="half right" ontablet="full-width" onmobile="full-width">
        <h1 layout="h-margin-15">
          <i class="material-icons" style="vertical-align: middle;">live_help</i>
            Envie uma pergunta
        </h1>
        <p layout="h-margin-15">
            Antes de perguntar, veja as <a href='/faqs/' text="big bolder">Perguntas e Respostas mais frequentes</a>.
        </p>
        <p  layout="h-margin-15">
            Se não encontrou a resposta para sua pergunta, envie então sua pergunta através
            do nossa <a href='/faqs/0/ask' text="big bolder">página de contato</a>.
        </p>
    </div>
</section>

apoio/apoio/templates/apoio/footer.html
    <footer layout="center full-width" text="center navy white line-1" links="hover-white fadeIn">
        <span text="smaller">
            Licença GNU GPL -
            <a href="https://www.gnu.org/licenses/gpl.html">Free Software Foundation</a>
        </span>
        <br>
        <span text="smaller">
            Feito com <a href='https://www.python.org'>Python</a>,
                <a href='https://djangoproject.com'>Django</a> e
                <a href='https://www.debian.org/'>Debian</a>
        </span>
        <br>
        <span text="smaller">
            <a href='https://github.com/piratas/apoio-piratas'>apoio-piratas@github</a><br>
        </span>
    </footer>

    <!-- jQuery -->
    <!--<script src="https://cdn.iikb.org/jquery/latest/jquery.min.js"></script>-->

    <!-- script -->
    <!--<script type="text/javascript">
    </script>-->

</body>
</html>

apoio/apoio/templates/apoio/header.html
{% load staticfiles %}

<!DOCTYPE html>
<html lang="en">
<head>

    <!-- meta -->
    <meta charset="utf-8">
    <meta name="description" content="">
    <meta name="keywords" content="" />
    <meta name="author" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1" />


    <title>APOIE OS PIRATAS</title>

    <!-- favicon -->
    <link rel="shortcut icon" href="" />
    <link rel="icon" href="{% static "favicon.ico" %}" type="image/x-icon" />

    <!-- Google Web Fonts -->
    <link href='https://www.google.com/fonts/specimen/Open+Sans' rel='stylesheet' type='text/css' />
    <link href='https://fonts.googleapis.com/css?family=Droid+Serif' rel='stylesheet' type='text/css' />
    <link href='https://www.google.com/fonts#UsePlace:use/Collection:Droid+Sans+Mono' rel='stylesheet' type='text/css' />

    <!-- Google Material Font Icon -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons" />

    <!-- The excelent http://helpers.araujo.cc plus our own CSS overlay -->
    <link rel="stylesheet" href="{% static "helpers.min.css" %}" />
    <link rel="stylesheet" href="{% static "piratas.css" %}" />

    <!--<link rel="stylesheet" href="http://openlayers.org/en/v3.15.1/css/ol.css" type="text/css">
        <script src="http://openlayers.org/en/v3.15.1/build/ol.js" type="text/javascript"></script>-->
</head>

<body text="line-1.5 gray-90" layout="no-margin" links="blue">

apoio/apoio/templates/apoio/index.html
{% include "header.html" %}

    <section id="landing" text="center navy white line-1" layout="center full-width fix">
        <h1 text="giant bolder" layout="h-margin-5">
            {{ SIGLA }}<br>
            <center>
                <a href="http://www.partidopirata.org/">
                    <img src="static/logo.pirata.svg" alt="PIRATAS" height="62" width="62" />
                </a>
            </center>
            {{ NOME }}
            <br>
            <span text="smaller light white" layout="h-margin-5">
                <small>Faça download da Ficha de Apoio e ajude a fundar o <code>PIRATAS</code></small>
            </span>
        </h1>
        <p>
          <a href="https://partidopirata.org/wp-content/uploads/2014/06/apoiamento.pdf" layout="rounded white no-border inline-block" text="bigger no-decoration" style="padding: 15px 40px; color: #522E91;">
            <i class="material-icons" style="vertical-align: middle;">assignment</i>
            Baixe a Ficha
          </a>
        </p>
    </section>

    {% include "texto_apoio.html" %}

    <section text="center" layout="center full-width fix">
        <div layout="v-padding-15">
            <img src="static/liberte_democracia_PIRATAS.jpg" alt="Liberte a Democracia com os PIRATAS" layout="top-40" />
        </div>
    </section>

    {% include "contatos.html" %}

{% include "footer.html" %}

apoio/apoio/templates/apoio/texto_apoio.html
<section id='quem' layout="center v-padding-30">

    <h1 layout="h-margin-15">
        <i class="material-icons" style="vertical-align: middle;">info</i> O que é o Partido Pirata?
    </h1>

    <p layout="h-margin-15">
        Somos um partido político em formação, com a sigla <strong><code>PIRATAS</code></strong>, que se
        pauta pela democracia plena, pela transparência pública e pelo
        empoderamento das pessoas, com o objetivo de defender
        institucionalmente os direitos humanos fundamentais por meio do
        respeito à diversidade social, à liberdade de crença (e descrença),
        aos direitos civis e políticos, à privacidade individual e à
        liberdade de expressão.
    </p>

    <p layout="h-margin-15">Quer saber mais sobre o <strong><code>PIRATAS</code></strong>? Leia nosso
        <a href='http://partidopirata.org/documentos/estatuto/' text="big bolder">Estatuto</a>
        e o nosso <a href='http://partidopirata.org/quem-somos/estrutura-nacional/documentos/programa/' text="big bolder">Programa</a>.
    </center>

    <h1 layout="h-margin-15 top-40">
        <i class="material-icons" style="vertical-align: middle;">record_voice_over</i>
        Como dar seu apoio?
    </h1>

    <p layout="h-margin-15">
    O <strong><strong><code>PIRATAS</code></strong></strong> precisa de 500 mil fichas de apoio assinadas por eleitores
        brasileiros em todo o país para obter seu registro como partido político.
        Isso só será possível com a sua participação. Contamos com a vossa
        colaboração para atingir a cota determinada pela legislação eleitoral e
        fazer com que os <strong><code>PIRATAS</code></strong> representem você no cenário político nacional.
    </p>

    <p layout="margin-30 padding-10 h-padding-20 gray-80 rounded" text="white">
    <span text="bolder bigger line-1">Atenção</span>: apoiar a criação do <strong><code>PIRATAS</code></strong>
        não significa filiação partidária e não gera nenhum outro vínculo ou
        responsabilidade legal com o partido. Apoiar a criação de partidos políticos
        É um direito seu no pleno exercício de sua cidadania.
    </p>

    <div layout="half left" ontablet="full-width" onmobile="full-width">
        <p layout="margin-15">
            Apoio individual
        </p>
        <ol layout="margin-15">
            <li>Imprima a ficha de apoio. Cada folha contém 3 fichas, preencha apenas uma delas</li>
            <li>Utilize caneta esferográfica e tenha seu Título de Eleitor em mãos</li>
            <li>Nome completo sem abreviações, inclua os dados de seu Título de Eleitor, zona eleitoral, seção e etc.<br>
                <span text="bold upper line-1 red">Tip</span>: Informações de Município e Estado são do local de emissão do título, não do seu local de nascimento</li>
            <li>Se não tiver seu Título de Eleitor em mãos acesse o site do TSE para obter os dados</li>
            <li>Se estiver com dificuldades para acessar o site do TSE coloque na ficha a data de seu nascimento e o nome completo de sua mãe, sem abreviações<br>
                <span text="bold upper line-1 red">Tip</span>: o nome completo de sua mãe precisa ser o nome que ela tem no título dela</li>
            <li>Assine a ficha de apoio antes de enviá-la pelo correio. Sua assinatura é a garantia de apoio ao <strong><code>PIRATAS</code></strong></li>
            <li>Envie sua ficha pelo correio para o endereço da Comitê Municipal de Coletas de Assinaturas de seu Estado.
                <a href='#' text="big bolder">Endereços Estaduais</a></li>
        </ol>
    </div>


    <div layout="half right" ontablet="full-width" onmobile="full-width">
        <p layout="margin-15">
        Seja coletor e nos ajude a colher assinaturas, sua ajuda é importantes no apoio ao <strong><code>PIRATAS</code></strong>.
        </p>

        <ol layout="margin-15">
            <li>Imprima a ficha de apoio. Cada folha contém 3 fichas</li>
            <li>Use caneta esferográfica nas fichas dos apoiadores que você conseguir, e informe o Títulos de Eleitor em cada apoio coletado</li>
            <li>Peça que informem o nome completo sem abreviações. Preencha as lacunas com os dados dos Títulos de Eleitor: zona eleitoral, seção e etc.<br>
                <span text="bold upper line-1 red">Tip</span>: Informações sobre Município e Estado são local de emissão do documento, não do local de nascimento</li>
            <li>Caso não tenha o Título de Eleitor em mãos, preencha os campos da data de nascimento e nome da mãe, sem abreviações.<br>
                <span text="bold upper line-1 red">Tip</span>: precisa ser o nome que a mãe do apoiador tem no título de eleitor</li>
            <li>Cada apoiador deverá assinar sua ficha. A assinatura é a garantia de apoio ao <strong><code>PIRATAS</code></strong></li>
            <li>Encaminhe as fichas de apoio para o endereço do Comitê Municipal de Coletas de Assinaturas de seu Estado.
                <a href='#' text='big bolder'>Endereços Estaduais</a></li>
            <li>Não espere acumular muitas fichas de apoio para enviar para a Comitê Municipal de Coletas de Assinaturas. Quanto antes elas chegarem, melhor</li>
        </ol>
    </div>

</section>

apoio/faqs/templates/faqs/detail.html
{% include "header.html" %}

    <h1 layout="margin-5">Respostas para as perguntas mais frequentes</h1>

    <section layout="h-margin-5 center">
        <div layout='table'>
            {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
          
            <form action="{% url 'faqs:index' %}" method="post">
                    <label>
                          <span>Nome</span><input id="name" type="text" name="name" />
                        </label> 
                      
                    <label>
                          <span>Email</span><input id="email" type="text" name="email" />
                        </label> 
              
                    <label>
                          <span>Pergunte</span><textarea id="question" name="question"></textarea>
                            <br>                     
                            <input type="submit" value="enviar" />
                        </label>
             </form>
        </div>
    </section>

{% include "footer.html" %}

apoio/faqs/templates/faqs/index.html
{% include "header.html" %}

    <section text="center" layout="center full-width fix">
        <h2>Perguntas e Respostas</h2>

        {% if latest_question_list %}

            {% for question in latest_question_list %}

                <p text="big"><a href="/faqs/{{ question.id }}/">{{ question.question_text }}</a></p>

            {% endfor %}

        {% else %}

            <p>Sem perguntas no momento.</p>

        {% endif %}
    </section>

{% include "footer.html" %}